name: GitHub Harvester 24/7

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours for full harvest
    - cron: '*/10 * * * *' # Every 10 minutes to check for assigned tasks
  workflow_dispatch:       # Manual trigger

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found. Installing default dependencies."
          pip install requests
        fi
    
    - name: Run Harvester
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        # Check if this is triggered by workflow_dispatch or the 2-hour schedule
        # If GITHUB_EVENT_NAME is workflow_dispatch or it's the top of an even hour, run full harvest
        CURRENT_MINUTE=$(date +%M)
        CURRENT_HOUR=$(date +%H)
        
        if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] || ([ "$CURRENT_MINUTE" = "00" ] && [ "$(($CURRENT_HOUR % 2))" = "0" ]); then
          echo "Running scheduled full harvest..."
          python harvester.py
        fi
        
        # Always check for assigned tasks
        echo "Checking for assigned tasks in agent-tasks repository..."
        # Get assigned tasks using curl
        ASSIGNED_TASKS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/zipaJopa/agent-tasks/issues?assignee=github-harvester-bot&state=open")
        
        # Check if there are any assigned tasks
        if echo "$ASSIGNED_TASKS" | grep -q "number"; then
          # Extract issue numbers and process each task
          echo "$ASSIGNED_TASKS" | grep -o '"number": [0-9]*' | grep -o '[0-9]*' | while read -r issue_number; do
            echo "Processing task #$issue_number"
            python harvester.py --task-mode --issue-number "$issue_number"
          done
        else
          echo "No tasks currently assigned to github-harvester-bot"
        fi
